<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxDiExp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxDiExp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxDiExp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxDiExp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxDiExp\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxDiExp',
    'container.build_id' => '866d68b9',
    'container.build_time' => 1695967095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxDiExp');
